# Renders the app icon from the header logo (lib/core/widgets/app_header_bar.dart)
# and writes it into the Android, iOS and web projects.
#
# The logo: a 24x24 box, two 18x18 squares with radius 5; the back one
# top-right and faint (lineStrong, stroke 1.4), the front one bottom-left (ink,
# stroke 1.8), both filled with bg. Colours are the light theme tokens.
#
# Run from stopka_flutter/:  python tool/make_icon.py   (needs Pillow)
import json
import os

from PIL import Image, ImageDraw

BG = (0xF3, 0xF2, 0xEF, 255)          # light.bg
INK = (0x17, 0x18, 0x1C, 255)         # light.ink
LINE_STRONG = (0xC9, 0xC7, 0xC0, 255) # light.lineStrong
CLEAR = (0, 0, 0, 0)
SS = 4  # supersampling for smooth edges


def logo(size, box, back, front, fill, canvas):
    """The logo in a size x size image, its 24-unit box `box` px wide, centred."""
    s = size * SS
    img = Image.new('RGBA', (s, s), canvas)
    d = ImageDraw.Draw(img)
    u = box * SS / 24.0
    o = (s - 24 * u) / 2

    def square(x, y, color, stroke):
        d.rounded_rectangle([o + x * u, o + y * u, o + (x + 18) * u, o + (y + 18) * u],
                            radius=5 * u, fill=fill, outline=color, width=max(1, round(stroke * u)))

    square(6, 0, back, 1.4)
    square(0, 6, front, 1.8)
    return img.resize((size, size), Image.LANCZOS)


# Masters. The adaptive foreground keeps the logo inside the 66dp safe circle
# of the 108dp canvas; the full icon fills about 60% of its square.
full = logo(1024, 600, LINE_STRONG, INK, BG, BG)
foreground = logo(1024, 480, LINE_STRONG, INK, BG, CLEAR)
# Themed icons: the system tints the alpha, so the back square is lighter.
monochrome = logo(1024, 480, (255, 255, 255, 110), (255, 255, 255, 255), CLEAR, CLEAR)
os.makedirs('assets/icon', exist_ok=True)
full.save('assets/icon/icon.png')
foreground.save('assets/icon/icon_foreground.png')
monochrome.save('assets/icon/icon_monochrome.png')


def save(img, size, path, alpha=True):
    out = img.resize((size, size), Image.LANCZOS)
    if not alpha:
        out = out.convert('RGB')  # iOS rejects icons with an alpha channel
    os.makedirs(os.path.dirname(path), exist_ok=True)
    out.save(path)


# Android: legacy icons, adaptive layers, and the adaptive-icon XML.
res = 'android/app/src/main/res'
for density, scale in [('mdpi', 1), ('hdpi', 1.5), ('xhdpi', 2), ('xxhdpi', 3), ('xxxhdpi', 4)]:
    save(full, round(48 * scale), f'{res}/mipmap-{density}/ic_launcher.png')
    save(foreground, round(108 * scale), f'{res}/mipmap-{density}/ic_launcher_foreground.png')
    save(monochrome, round(108 * scale), f'{res}/mipmap-{density}/ic_launcher_monochrome.png')
os.makedirs(f'{res}/mipmap-anydpi-v26', exist_ok=True)
with open(f'{res}/mipmap-anydpi-v26/ic_launcher.xml', 'w', newline='\n') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tool/make_icon.py -->\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@color/ic_launcher_background"/>\n'
            '    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>\n'
            '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>\n'
            '</adaptive-icon>\n')
with open(f'{res}/values/ic_launcher_background.xml', 'w', newline='\n') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tool/make_icon.py: DESIGN.md light bg -->\n'
            '<resources>\n'
            '    <color name="ic_launcher_background">#F3F2EF</color>\n'
            '</resources>\n')

# iOS: every size the asset catalogue lists.
catalogue = 'ios/Runner/Assets.xcassets/AppIcon.appiconset'
with open(f'{catalogue}/Contents.json') as f:
    for image in json.load(f)['images']:
        points = float(image['size'].split('x')[0])
        scale = int(image['scale'].rstrip('x'))
        save(full, round(points * scale), f"{catalogue}/{image['filename']}", alpha=False)

# Web: regular and maskable (logo inside the 80% safe zone) icons, favicon.
maskable = logo(1024, 480, LINE_STRONG, INK, BG, BG)
for size in (192, 512):
    save(full, size, f'web/icons/Icon-{size}.png')
    save(maskable, size, f'web/icons/Icon-maskable-{size}.png')
save(full, 32, 'web/favicon.png')
